version: '3.4'
services:
  secrets-manager-local:
    build:
      context: .
      target: dev
      dockerfile: ./deploy/Dockerfile
    volumes:
      - "./:/workspace"

  tests:
    build:
      context: .
      target: dev
      dockerfile: ./deploy/Dockerfile
    volumes:
      - "./:/workspace"
    command: >
      bash -c "pwd && mkdir -p controllers/$$ENVTEST_ASSETS_DIR &&
      test -f controllers/$$ENVTEST_ASSETS_DIR/setup-envtest.sh || curl -sSLo controllers/$$ENVTEST_ASSETS_DIR/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.3/hack/setup-envtest.sh &&
      source controllers/$$ENVTEST_ASSETS_DIR/setup-envtest.sh &&
      fetch_envtest_tools controllers/$$ENVTEST_ASSETS_DIR &&
      setup_envtest_env $$ENVTEST_ASSETS_DIR &&
      go test -v ./backend... ./errors/... ./controllers/... -coverprofile cover.out"

  secrets-manager:
    build:
      context: .
      target: release
      dockerfile: ./deploy/Dockerfile
