---
  version: 2.0

  jobs:
    unit_tests:
      docker:
      - image: circleci/golang:1.16
      environment:
        KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: "60s"
      steps:
      - checkout
      - setup_remote_docker
      - run: make test
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          when: always

    docker_hub_master:
      docker:
      - image: circleci/golang:1.16
      environment:
        KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: "60s"
      steps:
      - checkout
      - setup_remote_docker
      - run: make test

    docker_hub_release_tags:
      docker:
      - image: circleci/golang:1.16
      environment:
        KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: "60s"
      steps:
      - checkout
      - setup_remote_docker
      - run: make test

  workflows:
    version: 2
    secrets-manager:
      jobs:
      - unit_tests
      - docker_hub_master:
          requires:
          - unit_tests
          filters:
            branches:
              only: master
      - docker_hub_release_tags:
          requires:
          - unit_tests
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
