# permissions for end users to view secretdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretdefinition-viewer-role
rules:
- apiGroups:
  - secretsmanager.secrets-manager.tuenti.io
  resources:
  - secretdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secretsmanager.secrets-manager.tuenti.io
  resources:
  - secretdefinitions/status
  verbs:
  - get
